/*
=============================================================================
Exploratory Data Analysis (EDA)
=============================================================================
Script Purpose
    This script has the purpose to show some exploratory queries that can be
    used to understand the data. This will provide a data profiling view and
    general view of the biggest numbers for the company.

Contains:
    - Basic Queries
    - Simple Aggregations
    - Top N and Bottom N
=============================================================================
*/
-- Database Exploration
SELECT * FROM INFORMATION_SCHEMA.TABLES

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('dim_customers', 'dim_products', 'fact_sales')

-- Dimension Exploration
SELECT DISTINCT
	country
FROM gold.dim_customers

SELECT DISTINCT
	category,
	subcategory,
	product_name
FROM gold.dim_products
ORDER BY 1,2,3

-- Date Exploration
SELECT
	MIN(order_date) first_order_date,
	MAX(order_date) last_order_date,
	DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) order_range_years
FROM gold.fact_sales

SELECT
	MIN(birthdate) oldest_birthdate,
	DATEDIFF(YEAR,MIN(birthdate),GETDATE()) oldest_age,
	MAX(birthdate) youngest_birthdate,
	DATEDIFF(YEAR,MAX(birthdate),GETDATE()) youngest_age
FROM gold.dim_customers

-- Measure Exploration
-- Find the Total Sales
SELECT
	SUM(sales_amount) total_sales
FROM gold.fact_sales;

-- Find how many items are sold
SELECT
	SUM(quantity) items_sold
FROM gold.fact_sales;

-- Find the average selling price
SELECT
	AVG(price) average_price
FROM gold.fact_sales;

-- Find the Total number of Orders
SELECT
	COUNT(DISTINCT order_number) number_of_orders
FROM gold.fact_sales;

-- Find the Total number of products
SELECT
	COUNT(*) number_of_products
FROM gold.dim_products;

-- Find the total number of customers
SELECT
	COUNT(*) number_of_customers
FROM gold.dim_customers;

--Find the Total number of customers that has placed an order
SELECT
	COUNT(DISTINCT customer_key) total_customers
FROM gold.fact_sales

-- Generate report qith all the key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products' AS measure_name, COUNT(product_name) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers' AS measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total Nr. Customer with Orders' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales

-- Magnitude Analysis
-- Find Total customer by countries
SELECT
	country,
	COUNT(customer_id) total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_id) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find Total products by category
SELECT
	category,
	COUNT(product_id) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category
SELECT
	category,
	AVG(cost) avg_cost
FROM gold.dim_products pr
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated for each category
SELECT
	pr.category,
	SUM(sales_amount) total_sales
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products pr
ON fs.product_key = pr.product_key
GROUP BY category
ORDER BY total_sales DESC

--Find total revenue is generated by each customer
SELECT TOP 10
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(sales_amount) total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers c
ON fs.customer_key = c.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT
	c.country,
	SUM(quantity) items_sold
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers c
ON fs.customer_key = c.customer_key
GROUP BY country
ORDER BY items_sold DESC

-- Ranking Analysis
-- Which 5 products generate the highest revenue
SELECT TOP 5
	pr.product_name,
	SUM(sales_amount) total_revenue,
	SUM(quantity) total_items_sold
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products pr
ON fs.product_key = pr.product_key
GROUP BY product_name
ORDER BY total_revenue DESC

-- What are the 5 worst-performing products in terms of sales
SELECT TOP 5
	pr.product_name,
	SUM(sales_amount) total_revenue,
	SUM(quantity) total_items_sold
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products pr
ON fs.product_key = pr.product_key
GROUP BY product_name
ORDER BY total_revenue ASC
